//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: yorkie/v1/yorkie.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Yorkie is a service that provides a API for SDKs.
///
/// Usage: instantiate `Yorkie_V1_YorkieServiceClient`, then call methods of this protocol to make API calls.
internal protocol Yorkie_V1_YorkieServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? { get }

  func activateClient(
    _ request: Yorkie_V1_ActivateClientRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_ActivateClientRequest, Yorkie_V1_ActivateClientResponse>

  func deactivateClient(
    _ request: Yorkie_V1_DeactivateClientRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_DeactivateClientRequest, Yorkie_V1_DeactivateClientResponse>

  func updatePresence(
    _ request: Yorkie_V1_UpdatePresenceRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_UpdatePresenceRequest, Yorkie_V1_UpdatePresenceResponse>

  func attachDocument(
    _ request: Yorkie_V1_AttachDocumentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_AttachDocumentRequest, Yorkie_V1_AttachDocumentResponse>

  func detachDocument(
    _ request: Yorkie_V1_DetachDocumentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_DetachDocumentRequest, Yorkie_V1_DetachDocumentResponse>

  func watchDocuments(
    _ request: Yorkie_V1_WatchDocumentsRequest,
    callOptions: CallOptions?,
    handler: @escaping (Yorkie_V1_WatchDocumentsResponse) -> Void
  ) -> ServerStreamingCall<Yorkie_V1_WatchDocumentsRequest, Yorkie_V1_WatchDocumentsResponse>

  func pushPull(
    _ request: Yorkie_V1_PushPullRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_PushPullRequest, Yorkie_V1_PushPullResponse>
}

extension Yorkie_V1_YorkieServiceClientProtocol {
  internal var serviceName: String {
    return "yorkie.v1.YorkieService"
  }

  /// Unary call to ActivateClient
  ///
  /// - Parameters:
  ///   - request: Request to send to ActivateClient.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func activateClient(
    _ request: Yorkie_V1_ActivateClientRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_ActivateClientRequest, Yorkie_V1_ActivateClientResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.activateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeActivateClientInterceptors() ?? []
    )
  }

  /// Unary call to DeactivateClient
  ///
  /// - Parameters:
  ///   - request: Request to send to DeactivateClient.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deactivateClient(
    _ request: Yorkie_V1_DeactivateClientRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_DeactivateClientRequest, Yorkie_V1_DeactivateClientResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.deactivateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeactivateClientInterceptors() ?? []
    )
  }

  /// Unary call to UpdatePresence
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdatePresence.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updatePresence(
    _ request: Yorkie_V1_UpdatePresenceRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_UpdatePresenceRequest, Yorkie_V1_UpdatePresenceResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.updatePresence.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePresenceInterceptors() ?? []
    )
  }

  /// Unary call to AttachDocument
  ///
  /// - Parameters:
  ///   - request: Request to send to AttachDocument.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func attachDocument(
    _ request: Yorkie_V1_AttachDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_AttachDocumentRequest, Yorkie_V1_AttachDocumentResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.attachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAttachDocumentInterceptors() ?? []
    )
  }

  /// Unary call to DetachDocument
  ///
  /// - Parameters:
  ///   - request: Request to send to DetachDocument.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func detachDocument(
    _ request: Yorkie_V1_DetachDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_DetachDocumentRequest, Yorkie_V1_DetachDocumentResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.detachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDetachDocumentInterceptors() ?? []
    )
  }

  /// Server streaming call to WatchDocuments
  ///
  /// - Parameters:
  ///   - request: Request to send to WatchDocuments.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func watchDocuments(
    _ request: Yorkie_V1_WatchDocumentsRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Yorkie_V1_WatchDocumentsResponse) -> Void
  ) -> ServerStreamingCall<Yorkie_V1_WatchDocumentsRequest, Yorkie_V1_WatchDocumentsResponse> {
    return self.makeServerStreamingCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.watchDocuments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWatchDocumentsInterceptors() ?? [],
      handler: handler
    )
  }

  /// Unary call to PushPull
  ///
  /// - Parameters:
  ///   - request: Request to send to PushPull.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func pushPull(
    _ request: Yorkie_V1_PushPullRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_PushPullRequest, Yorkie_V1_PushPullResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.pushPull.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePushPullInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Yorkie_V1_YorkieServiceClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Yorkie_V1_YorkieServiceNIOClient")
internal final class Yorkie_V1_YorkieServiceClient: Yorkie_V1_YorkieServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the yorkie.v1.YorkieService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Yorkie_V1_YorkieServiceNIOClient: Yorkie_V1_YorkieServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the yorkie.v1.YorkieService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Yorkie is a service that provides a API for SDKs.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Yorkie_V1_YorkieServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? { get }

  func makeActivateClientCall(
    _ request: Yorkie_V1_ActivateClientRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_ActivateClientRequest, Yorkie_V1_ActivateClientResponse>

  func makeDeactivateClientCall(
    _ request: Yorkie_V1_DeactivateClientRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_DeactivateClientRequest, Yorkie_V1_DeactivateClientResponse>

  func makeUpdatePresenceCall(
    _ request: Yorkie_V1_UpdatePresenceRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_UpdatePresenceRequest, Yorkie_V1_UpdatePresenceResponse>

  func makeAttachDocumentCall(
    _ request: Yorkie_V1_AttachDocumentRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_AttachDocumentRequest, Yorkie_V1_AttachDocumentResponse>

  func makeDetachDocumentCall(
    _ request: Yorkie_V1_DetachDocumentRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_DetachDocumentRequest, Yorkie_V1_DetachDocumentResponse>

  func makeWatchDocumentsCall(
    _ request: Yorkie_V1_WatchDocumentsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Yorkie_V1_WatchDocumentsRequest, Yorkie_V1_WatchDocumentsResponse>

  func makePushPullCall(
    _ request: Yorkie_V1_PushPullRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_PushPullRequest, Yorkie_V1_PushPullResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Yorkie_V1_YorkieServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Yorkie_V1_YorkieServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeActivateClientCall(
    _ request: Yorkie_V1_ActivateClientRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_ActivateClientRequest, Yorkie_V1_ActivateClientResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.activateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeActivateClientInterceptors() ?? []
    )
  }

  internal func makeDeactivateClientCall(
    _ request: Yorkie_V1_DeactivateClientRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_DeactivateClientRequest, Yorkie_V1_DeactivateClientResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.deactivateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeactivateClientInterceptors() ?? []
    )
  }

  internal func makeUpdatePresenceCall(
    _ request: Yorkie_V1_UpdatePresenceRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_UpdatePresenceRequest, Yorkie_V1_UpdatePresenceResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.updatePresence.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePresenceInterceptors() ?? []
    )
  }

  internal func makeAttachDocumentCall(
    _ request: Yorkie_V1_AttachDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_AttachDocumentRequest, Yorkie_V1_AttachDocumentResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.attachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAttachDocumentInterceptors() ?? []
    )
  }

  internal func makeDetachDocumentCall(
    _ request: Yorkie_V1_DetachDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_DetachDocumentRequest, Yorkie_V1_DetachDocumentResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.detachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDetachDocumentInterceptors() ?? []
    )
  }

  internal func makeWatchDocumentsCall(
    _ request: Yorkie_V1_WatchDocumentsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Yorkie_V1_WatchDocumentsRequest, Yorkie_V1_WatchDocumentsResponse> {
    return self.makeAsyncServerStreamingCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.watchDocuments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWatchDocumentsInterceptors() ?? []
    )
  }

  internal func makePushPullCall(
    _ request: Yorkie_V1_PushPullRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_PushPullRequest, Yorkie_V1_PushPullResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.pushPull.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePushPullInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Yorkie_V1_YorkieServiceAsyncClientProtocol {
  internal func activateClient(
    _ request: Yorkie_V1_ActivateClientRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_ActivateClientResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.activateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeActivateClientInterceptors() ?? []
    )
  }

  internal func deactivateClient(
    _ request: Yorkie_V1_DeactivateClientRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_DeactivateClientResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.deactivateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeactivateClientInterceptors() ?? []
    )
  }

  internal func updatePresence(
    _ request: Yorkie_V1_UpdatePresenceRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_UpdatePresenceResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.updatePresence.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePresenceInterceptors() ?? []
    )
  }

  internal func attachDocument(
    _ request: Yorkie_V1_AttachDocumentRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_AttachDocumentResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.attachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAttachDocumentInterceptors() ?? []
    )
  }

  internal func detachDocument(
    _ request: Yorkie_V1_DetachDocumentRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_DetachDocumentResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.detachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDetachDocumentInterceptors() ?? []
    )
  }

  internal func watchDocuments(
    _ request: Yorkie_V1_WatchDocumentsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Yorkie_V1_WatchDocumentsResponse> {
    return self.performAsyncServerStreamingCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.watchDocuments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWatchDocumentsInterceptors() ?? []
    )
  }

  internal func pushPull(
    _ request: Yorkie_V1_PushPullRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_PushPullResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.pushPull.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePushPullInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Yorkie_V1_YorkieServiceAsyncClient: Yorkie_V1_YorkieServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

internal protocol Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'activateClient'.
  func makeActivateClientInterceptors() -> [ClientInterceptor<Yorkie_V1_ActivateClientRequest, Yorkie_V1_ActivateClientResponse>]

  /// - Returns: Interceptors to use when invoking 'deactivateClient'.
  func makeDeactivateClientInterceptors() -> [ClientInterceptor<Yorkie_V1_DeactivateClientRequest, Yorkie_V1_DeactivateClientResponse>]

  /// - Returns: Interceptors to use when invoking 'updatePresence'.
  func makeUpdatePresenceInterceptors() -> [ClientInterceptor<Yorkie_V1_UpdatePresenceRequest, Yorkie_V1_UpdatePresenceResponse>]

  /// - Returns: Interceptors to use when invoking 'attachDocument'.
  func makeAttachDocumentInterceptors() -> [ClientInterceptor<Yorkie_V1_AttachDocumentRequest, Yorkie_V1_AttachDocumentResponse>]

  /// - Returns: Interceptors to use when invoking 'detachDocument'.
  func makeDetachDocumentInterceptors() -> [ClientInterceptor<Yorkie_V1_DetachDocumentRequest, Yorkie_V1_DetachDocumentResponse>]

  /// - Returns: Interceptors to use when invoking 'watchDocuments'.
  func makeWatchDocumentsInterceptors() -> [ClientInterceptor<Yorkie_V1_WatchDocumentsRequest, Yorkie_V1_WatchDocumentsResponse>]

  /// - Returns: Interceptors to use when invoking 'pushPull'.
  func makePushPullInterceptors() -> [ClientInterceptor<Yorkie_V1_PushPullRequest, Yorkie_V1_PushPullResponse>]
}

internal enum Yorkie_V1_YorkieServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "YorkieService",
    fullName: "yorkie.v1.YorkieService",
    methods: [
      Yorkie_V1_YorkieServiceClientMetadata.Methods.activateClient,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.deactivateClient,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.updatePresence,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.attachDocument,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.detachDocument,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.watchDocuments,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.pushPull,
    ]
  )

  internal enum Methods {
    internal static let activateClient = GRPCMethodDescriptor(
      name: "ActivateClient",
      path: "/yorkie.v1.YorkieService/ActivateClient",
      type: GRPCCallType.unary
    )

    internal static let deactivateClient = GRPCMethodDescriptor(
      name: "DeactivateClient",
      path: "/yorkie.v1.YorkieService/DeactivateClient",
      type: GRPCCallType.unary
    )

    internal static let updatePresence = GRPCMethodDescriptor(
      name: "UpdatePresence",
      path: "/yorkie.v1.YorkieService/UpdatePresence",
      type: GRPCCallType.unary
    )

    internal static let attachDocument = GRPCMethodDescriptor(
      name: "AttachDocument",
      path: "/yorkie.v1.YorkieService/AttachDocument",
      type: GRPCCallType.unary
    )

    internal static let detachDocument = GRPCMethodDescriptor(
      name: "DetachDocument",
      path: "/yorkie.v1.YorkieService/DetachDocument",
      type: GRPCCallType.unary
    )

    internal static let watchDocuments = GRPCMethodDescriptor(
      name: "WatchDocuments",
      path: "/yorkie.v1.YorkieService/WatchDocuments",
      type: GRPCCallType.serverStreaming
    )

    internal static let pushPull = GRPCMethodDescriptor(
      name: "PushPull",
      path: "/yorkie.v1.YorkieService/PushPull",
      type: GRPCCallType.unary
    )
  }
}

