//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: yorkie/v1/yorkie.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Yorkie is a service that provides a API for SDKs.
///
/// Usage: instantiate `Yorkie_V1_YorkieServiceClient`, then call methods of this protocol to make API calls.
internal protocol Yorkie_V1_YorkieServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? { get }

  func activateClient(
    _ request: Yorkie_V1_ActivateClientRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_ActivateClientRequest, Yorkie_V1_ActivateClientResponse>

  func deactivateClient(
    _ request: Yorkie_V1_DeactivateClientRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_DeactivateClientRequest, Yorkie_V1_DeactivateClientResponse>

  func attachDocument(
    _ request: Yorkie_V1_AttachDocumentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_AttachDocumentRequest, Yorkie_V1_AttachDocumentResponse>

  func detachDocument(
    _ request: Yorkie_V1_DetachDocumentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_DetachDocumentRequest, Yorkie_V1_DetachDocumentResponse>

  func removeDocument(
    _ request: Yorkie_V1_RemoveDocumentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_RemoveDocumentRequest, Yorkie_V1_RemoveDocumentResponse>

  func pushPullChanges(
    _ request: Yorkie_V1_PushPullChangesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_PushPullChangesRequest, Yorkie_V1_PushPullChangesResponse>

  func watchDocument(
    _ request: Yorkie_V1_WatchDocumentRequest,
    callOptions: CallOptions?,
    handler: @escaping (Yorkie_V1_WatchDocumentResponse) -> Void
  ) -> ServerStreamingCall<Yorkie_V1_WatchDocumentRequest, Yorkie_V1_WatchDocumentResponse>

  func broadcast(
    _ request: Yorkie_V1_BroadcastRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Yorkie_V1_BroadcastRequest, Yorkie_V1_BroadcastResponse>
}

extension Yorkie_V1_YorkieServiceClientProtocol {
  internal var serviceName: String {
    return "yorkie.v1.YorkieService"
  }

  /// Unary call to ActivateClient
  ///
  /// - Parameters:
  ///   - request: Request to send to ActivateClient.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func activateClient(
    _ request: Yorkie_V1_ActivateClientRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_ActivateClientRequest, Yorkie_V1_ActivateClientResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.activateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeActivateClientInterceptors() ?? []
    )
  }

  /// Unary call to DeactivateClient
  ///
  /// - Parameters:
  ///   - request: Request to send to DeactivateClient.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deactivateClient(
    _ request: Yorkie_V1_DeactivateClientRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_DeactivateClientRequest, Yorkie_V1_DeactivateClientResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.deactivateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeactivateClientInterceptors() ?? []
    )
  }

  /// Unary call to AttachDocument
  ///
  /// - Parameters:
  ///   - request: Request to send to AttachDocument.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func attachDocument(
    _ request: Yorkie_V1_AttachDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_AttachDocumentRequest, Yorkie_V1_AttachDocumentResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.attachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAttachDocumentInterceptors() ?? []
    )
  }

  /// Unary call to DetachDocument
  ///
  /// - Parameters:
  ///   - request: Request to send to DetachDocument.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func detachDocument(
    _ request: Yorkie_V1_DetachDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_DetachDocumentRequest, Yorkie_V1_DetachDocumentResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.detachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDetachDocumentInterceptors() ?? []
    )
  }

  /// Unary call to RemoveDocument
  ///
  /// - Parameters:
  ///   - request: Request to send to RemoveDocument.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func removeDocument(
    _ request: Yorkie_V1_RemoveDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_RemoveDocumentRequest, Yorkie_V1_RemoveDocumentResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.removeDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoveDocumentInterceptors() ?? []
    )
  }

  /// Unary call to PushPullChanges
  ///
  /// - Parameters:
  ///   - request: Request to send to PushPullChanges.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func pushPullChanges(
    _ request: Yorkie_V1_PushPullChangesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_PushPullChangesRequest, Yorkie_V1_PushPullChangesResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.pushPullChanges.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePushPullChangesInterceptors() ?? []
    )
  }

  /// Server streaming call to WatchDocument
  ///
  /// - Parameters:
  ///   - request: Request to send to WatchDocument.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func watchDocument(
    _ request: Yorkie_V1_WatchDocumentRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Yorkie_V1_WatchDocumentResponse) -> Void
  ) -> ServerStreamingCall<Yorkie_V1_WatchDocumentRequest, Yorkie_V1_WatchDocumentResponse> {
    return self.makeServerStreamingCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.watchDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWatchDocumentInterceptors() ?? [],
      handler: handler
    )
  }

  /// Unary call to Broadcast
  ///
  /// - Parameters:
  ///   - request: Request to send to Broadcast.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func broadcast(
    _ request: Yorkie_V1_BroadcastRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Yorkie_V1_BroadcastRequest, Yorkie_V1_BroadcastResponse> {
    return self.makeUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.broadcast.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBroadcastInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Yorkie_V1_YorkieServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Yorkie_V1_YorkieServiceNIOClient")
internal final class Yorkie_V1_YorkieServiceClient: Yorkie_V1_YorkieServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the yorkie.v1.YorkieService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Yorkie_V1_YorkieServiceNIOClient: Yorkie_V1_YorkieServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the yorkie.v1.YorkieService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Yorkie is a service that provides a API for SDKs.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Yorkie_V1_YorkieServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? { get }

  func makeActivateClientCall(
    _ request: Yorkie_V1_ActivateClientRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_ActivateClientRequest, Yorkie_V1_ActivateClientResponse>

  func makeDeactivateClientCall(
    _ request: Yorkie_V1_DeactivateClientRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_DeactivateClientRequest, Yorkie_V1_DeactivateClientResponse>

  func makeAttachDocumentCall(
    _ request: Yorkie_V1_AttachDocumentRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_AttachDocumentRequest, Yorkie_V1_AttachDocumentResponse>

  func makeDetachDocumentCall(
    _ request: Yorkie_V1_DetachDocumentRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_DetachDocumentRequest, Yorkie_V1_DetachDocumentResponse>

  func makeRemoveDocumentCall(
    _ request: Yorkie_V1_RemoveDocumentRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_RemoveDocumentRequest, Yorkie_V1_RemoveDocumentResponse>

  func makePushPullChangesCall(
    _ request: Yorkie_V1_PushPullChangesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_PushPullChangesRequest, Yorkie_V1_PushPullChangesResponse>

  func makeWatchDocumentCall(
    _ request: Yorkie_V1_WatchDocumentRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Yorkie_V1_WatchDocumentRequest, Yorkie_V1_WatchDocumentResponse>

  func makeBroadcastCall(
    _ request: Yorkie_V1_BroadcastRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_BroadcastRequest, Yorkie_V1_BroadcastResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Yorkie_V1_YorkieServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Yorkie_V1_YorkieServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeActivateClientCall(
    _ request: Yorkie_V1_ActivateClientRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_ActivateClientRequest, Yorkie_V1_ActivateClientResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.activateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeActivateClientInterceptors() ?? []
    )
  }

  internal func makeDeactivateClientCall(
    _ request: Yorkie_V1_DeactivateClientRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_DeactivateClientRequest, Yorkie_V1_DeactivateClientResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.deactivateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeactivateClientInterceptors() ?? []
    )
  }

  internal func makeAttachDocumentCall(
    _ request: Yorkie_V1_AttachDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_AttachDocumentRequest, Yorkie_V1_AttachDocumentResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.attachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAttachDocumentInterceptors() ?? []
    )
  }

  internal func makeDetachDocumentCall(
    _ request: Yorkie_V1_DetachDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_DetachDocumentRequest, Yorkie_V1_DetachDocumentResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.detachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDetachDocumentInterceptors() ?? []
    )
  }

  internal func makeRemoveDocumentCall(
    _ request: Yorkie_V1_RemoveDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_RemoveDocumentRequest, Yorkie_V1_RemoveDocumentResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.removeDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoveDocumentInterceptors() ?? []
    )
  }

  internal func makePushPullChangesCall(
    _ request: Yorkie_V1_PushPullChangesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_PushPullChangesRequest, Yorkie_V1_PushPullChangesResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.pushPullChanges.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePushPullChangesInterceptors() ?? []
    )
  }

  internal func makeWatchDocumentCall(
    _ request: Yorkie_V1_WatchDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Yorkie_V1_WatchDocumentRequest, Yorkie_V1_WatchDocumentResponse> {
    return self.makeAsyncServerStreamingCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.watchDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWatchDocumentInterceptors() ?? []
    )
  }

  internal func makeBroadcastCall(
    _ request: Yorkie_V1_BroadcastRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Yorkie_V1_BroadcastRequest, Yorkie_V1_BroadcastResponse> {
    return self.makeAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.broadcast.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBroadcastInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Yorkie_V1_YorkieServiceAsyncClientProtocol {
  internal func activateClient(
    _ request: Yorkie_V1_ActivateClientRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_ActivateClientResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.activateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeActivateClientInterceptors() ?? []
    )
  }

  internal func deactivateClient(
    _ request: Yorkie_V1_DeactivateClientRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_DeactivateClientResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.deactivateClient.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeactivateClientInterceptors() ?? []
    )
  }

  internal func attachDocument(
    _ request: Yorkie_V1_AttachDocumentRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_AttachDocumentResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.attachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAttachDocumentInterceptors() ?? []
    )
  }

  internal func detachDocument(
    _ request: Yorkie_V1_DetachDocumentRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_DetachDocumentResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.detachDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDetachDocumentInterceptors() ?? []
    )
  }

  internal func removeDocument(
    _ request: Yorkie_V1_RemoveDocumentRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_RemoveDocumentResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.removeDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoveDocumentInterceptors() ?? []
    )
  }

  internal func pushPullChanges(
    _ request: Yorkie_V1_PushPullChangesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_PushPullChangesResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.pushPullChanges.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePushPullChangesInterceptors() ?? []
    )
  }

  internal func watchDocument(
    _ request: Yorkie_V1_WatchDocumentRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Yorkie_V1_WatchDocumentResponse> {
    return self.performAsyncServerStreamingCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.watchDocument.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWatchDocumentInterceptors() ?? []
    )
  }

  internal func broadcast(
    _ request: Yorkie_V1_BroadcastRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Yorkie_V1_BroadcastResponse {
    return try await self.performAsyncUnaryCall(
      path: Yorkie_V1_YorkieServiceClientMetadata.Methods.broadcast.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBroadcastInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Yorkie_V1_YorkieServiceAsyncClient: Yorkie_V1_YorkieServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Yorkie_V1_YorkieServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'activateClient'.
  func makeActivateClientInterceptors() -> [ClientInterceptor<Yorkie_V1_ActivateClientRequest, Yorkie_V1_ActivateClientResponse>]

  /// - Returns: Interceptors to use when invoking 'deactivateClient'.
  func makeDeactivateClientInterceptors() -> [ClientInterceptor<Yorkie_V1_DeactivateClientRequest, Yorkie_V1_DeactivateClientResponse>]

  /// - Returns: Interceptors to use when invoking 'attachDocument'.
  func makeAttachDocumentInterceptors() -> [ClientInterceptor<Yorkie_V1_AttachDocumentRequest, Yorkie_V1_AttachDocumentResponse>]

  /// - Returns: Interceptors to use when invoking 'detachDocument'.
  func makeDetachDocumentInterceptors() -> [ClientInterceptor<Yorkie_V1_DetachDocumentRequest, Yorkie_V1_DetachDocumentResponse>]

  /// - Returns: Interceptors to use when invoking 'removeDocument'.
  func makeRemoveDocumentInterceptors() -> [ClientInterceptor<Yorkie_V1_RemoveDocumentRequest, Yorkie_V1_RemoveDocumentResponse>]

  /// - Returns: Interceptors to use when invoking 'pushPullChanges'.
  func makePushPullChangesInterceptors() -> [ClientInterceptor<Yorkie_V1_PushPullChangesRequest, Yorkie_V1_PushPullChangesResponse>]

  /// - Returns: Interceptors to use when invoking 'watchDocument'.
  func makeWatchDocumentInterceptors() -> [ClientInterceptor<Yorkie_V1_WatchDocumentRequest, Yorkie_V1_WatchDocumentResponse>]

  /// - Returns: Interceptors to use when invoking 'broadcast'.
  func makeBroadcastInterceptors() -> [ClientInterceptor<Yorkie_V1_BroadcastRequest, Yorkie_V1_BroadcastResponse>]
}

internal enum Yorkie_V1_YorkieServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "YorkieService",
    fullName: "yorkie.v1.YorkieService",
    methods: [
      Yorkie_V1_YorkieServiceClientMetadata.Methods.activateClient,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.deactivateClient,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.attachDocument,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.detachDocument,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.removeDocument,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.pushPullChanges,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.watchDocument,
      Yorkie_V1_YorkieServiceClientMetadata.Methods.broadcast,
    ]
  )

  internal enum Methods {
    internal static let activateClient = GRPCMethodDescriptor(
      name: "ActivateClient",
      path: "/yorkie.v1.YorkieService/ActivateClient",
      type: GRPCCallType.unary
    )

    internal static let deactivateClient = GRPCMethodDescriptor(
      name: "DeactivateClient",
      path: "/yorkie.v1.YorkieService/DeactivateClient",
      type: GRPCCallType.unary
    )

    internal static let attachDocument = GRPCMethodDescriptor(
      name: "AttachDocument",
      path: "/yorkie.v1.YorkieService/AttachDocument",
      type: GRPCCallType.unary
    )

    internal static let detachDocument = GRPCMethodDescriptor(
      name: "DetachDocument",
      path: "/yorkie.v1.YorkieService/DetachDocument",
      type: GRPCCallType.unary
    )

    internal static let removeDocument = GRPCMethodDescriptor(
      name: "RemoveDocument",
      path: "/yorkie.v1.YorkieService/RemoveDocument",
      type: GRPCCallType.unary
    )

    internal static let pushPullChanges = GRPCMethodDescriptor(
      name: "PushPullChanges",
      path: "/yorkie.v1.YorkieService/PushPullChanges",
      type: GRPCCallType.unary
    )

    internal static let watchDocument = GRPCMethodDescriptor(
      name: "WatchDocument",
      path: "/yorkie.v1.YorkieService/WatchDocument",
      type: GRPCCallType.serverStreaming
    )

    internal static let broadcast = GRPCMethodDescriptor(
      name: "Broadcast",
      path: "/yorkie.v1.YorkieService/Broadcast",
      type: GRPCCallType.unary
    )
  }
}

